## Github actions to execute  deploy-ENV jobs based on branch

name: deploy_ENV

on:
  push:
    branches:
      - stage

env:
  JENKINS_HOST: https://jenkins.bodeboca.com

jobs:
  launch_jenkins_deploy:
    name: Launch jenkins deploy-ENV job
    runs-on: ubuntu-latest
    steps:
      -
        name: Decide Jenkins job to run
        uses: kanga333/variable-mapper@master
        with:
          key: ${{ github.ref }}
          map: |
            {
              "stage": {
                "JENKINS_JOB": "${{ secrets.BB_JENKINS_JOB_DEPLOY_STAGE }}"
              }
            }
      -
        name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@v1.3
        with:
          JENKINS_USER: ${{ secrets.BB_JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.BB_JENKINS_TOKEN }}
          JENKINS_HOST: ${{ env.JENKINS_HOST }}
          JENKINS_JOB: ${{ env.JENKINS_JOB }}
