## Github actions to execute jobs based on branch
## TODO
## Añadir new step que comprueba en que rama se esta pusheando el job y a partir de ello darle valor a JENKINS_JOB
##
name: deploy_ENV

on:
  push:
    branches:
      ## Execute deploy-devel
      - dev
      ## Execute deploy-stg
      - production

jobs:
  launch_jenkins_deploy:
    name: Launch jenkins deploy-ENV job
    runs-on: ubuntu-latest
    env:
      JENKINS_JOB: placeholder
##    environment: https://jenkins.sbit.io/
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: Decide which Jenkins job to run
        env:
          GITHUB_REF: "github.ref"
        run: |
          if ["$GITHUB_REF" = "refs/heads/dev"]; then
            $JENKINS_JOB = "admin/dev/sbitio-github/deploy-ENV/deploy-devel"
          elif ["$GITHUB_REF" = "refs/heads/production"]; then
            $JENKINS_JOB = "admin/dev/sbitio-github/deploy-ENV/deploy-staging"
          fi
      -
        name: Trigger Jenkins Job
        if: ${{ env.JENKINS_JOB }} != 'placeholder'
        uses: docker://registry.gitlab.com/sbitio/gitlab-ci:latest
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        with:
          args: "-h ${{ secrets.JENKINS_HOST }} -j ${{ env.JENKINS_JOB }}"
#      -
#        name: Trigger Jenkins Job deploy-STG
#        if: github.ref == 'refs/heads/production'
#        uses: docker://registry.gitlab.com/sbitio/gitlab-ci:latest
#        env:
#          JENKINS_USER: ${{ secrets.JENKINS_USER }}
#          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
#        with:
#          args: "-h https://jenkins.sbit.io/ -j admin/dev/sbitio-github/deploy-ENV/deploy-staging"
