## Github actions to execute jobs based on branch
## TODO
## Añadir new step que comprueba en que rama se esta pusheando el job y a partir de ello darle valor a JENKINS_JOB
##
name: deploy_ENV

on:
  push:
    branches:
      ## Execute deploy-devel
      - dev
      ## Execute deploy-stg
      - production

jobs:
  launch_jenkins_deploy:
    name: Launch jenkins deploy-ENV job
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: Decide which Jenkins job to run
        id: decide_jenkins_job
        env:
          GITHUB_REF: github.ref
          job_for_dev: admin/dev/sbitio-github/deploy-ENV/deploy-devel
          job_for_production: admin/dev/sbitio-github/deploy-ENV/deploy-staging
        run: |
          echo ${GITHUB_REF##r*/}
          echo "JENKINS_JOB=$job_for_${{ env.GITHUB_REF##r*/ }}">> $GITHUB_ENV
      -
        name: Trigger Jenkins Job
        if: ${{ env.JENKINS_JOB }} != 'placeholder'
        uses: docker://registry.gitlab.com/sbitio/gitlab-ci:latest
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        with:
          args: "-h ${{ secrets.JENKINS_HOST }} -j ${{ env.JENKINS_JOB }}"
#      -
#        name: Trigger Jenkins Job deploy-STG
#        if: github.ref == 'refs/heads/production'
#        uses: docker://registry.gitlab.com/sbitio/gitlab-ci:latest
#        env:
#          JENKINS_USER: ${{ secrets.JENKINS_USER }}
#          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
#        with:
#          args: "-h https://jenkins.sbit.io/ -j admin/dev/sbitio-github/deploy-ENV/deploy-staging"

#        run: |
#          if [ ${GITHUB_REF} = 'refs/heads/dev' ]; then
#            echo "JENKINS_JOB=admin/dev/sbitio-github/deploy-ENV/deploy-devel" >> $GITHUB_ENV
#          elif [ ${GITHUB_REF} = 'refs/heads/production' ]; then
#            echo "JENKINS_JOB=admin/dev/sbitio-github/deploy-ENV/deploy-staging" >> $GITHUB_ENV
#          fi
